version: '3'

services:
  dtn-server-1:
    build:
      context: ./
      dockerfile: dockerfile/Dockerfile1
    container_name: "dtn1"
    ports:
      - "50001:5001/tcp"
      - "50001:5001/udp"
    networks:
      fixed_compose_network:
        ipv4_address: 172.16.238.2
    volumes: 
      - ./dtnconf/host149.rc:/dtnconf/host149.rc
    tty: true

  dtn-server-2:
    build:
      context: ./
      dockerfile: dockerfile/Dockerfile2
    container_name: "dtn2"
    ports:
      - "50002:5001/tcp"
      - "50002:5001/udp"
    networks:
      fixed_compose_network:
        ipv4_address: 172.16.238.3
    volumes: 
      - ./dtnconf/host150.rc:/dtnconf/host150.rc
    tty: true

networks:
  fixed_compose_network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24